### ISSUE TITLE
Mudanças da NBR 6023 de 2018

### ISSUE THREAD

**Issue by douglasrizzo** [abntex/biblatex-abnt#64]
Olá, eu reparei que a NBR 6023 de 2018 incluiu mudanças que podem não estar refletidas no biblatex-abnt. Encontrei uma lista amigável das mudanças (pra não ter que comparar as duas normas do início ao fim) [aqui](https://www2.unesp.br/Home/cgb/informativo-gnt---nbr-6023---02-05-2019.pdf).

Com relação à formatação mais simples, eu separei as seguintes divergências:

- [x] o espaçamento entre as entradas nas referências é simples  (feito #66)
- [x] não é mais usado o travessão _____ quando os nomes dos autores se repetem (feito #67)
- [x] não se usa mais <> nas URLs (resolvido na branch dev)
- [x] as expressões “[s.l.]” e “[s.n.]” são em itálico (feito #65)
- [x] as expressões “In” e “et al.” são em itálico (feito #69)
- [x] Termos como "Anais..." agora colocam as reticências entre colchetes: "Anais [...]" (feito manualmente #70)

Ainda existem algumas outras coisas estranhas, como marcar nome de editor por (ed.) e usar o nome do país na localização da referências, quando cidade e estado não estão disponíveis, mas acho que as supracitadas são mais gerais e beneficiariam a todos os usuários do pacote.

## Soluções

- O espaçamento entre entradas pode ser resolvido redefinindo `\bibitemsep`: https://tex.stackexchange.com/a/19109
- O travessão é removido com a opção `repeatfields=true` do biblatex (não requer mudanças no `biblatex-abnt`, mas deveria ser o comportamento padrão daqui pra frente?)
- O <> pode ser removido da URL mudando a seguinte linha: https://github.com/abntex/biblatex-abnt/blob/4825f196b9232bb2424d48e002093080fa08e510/latex/bbx/abnt.bbx#L720
- As expressões em itálico, eu não sei como mudar.

**Comment by douglasrizzo** [comment]
Na verdade, eu levantei o espaço entre entradas, mas a norma (seção 6.3) menciona isso:

> As referências devem ser elaboradas em espaço simples, alinhadas à margem esquerda do texto **e separadas entre si por uma linha em branco de espaço simples**.

Já é incluída uma linha entre as entradas, então pode ser que isso esteja certo.

**Comment by dbmrq** [comment]
Obrigado, sua lista vai ajudar muito e, se quiser ir adiantando algum desses itens e fazer uma PR, vai ajudar mais ainda! :D

**Comment by douglasrizzo** [comment]
Admito que eu sempre quis contribuir com o projeto, porque sou responsável por uma classe que é bastante usada e depende do `biblatex-abnt`. Mas quando eu abro aqueles arquivos cbx e bbx, não entendo nada, hahahaha. Aquilo é Latex? Latex 3? Alguma linguagem que só o Biber compreende?

Se você conseguir me apontar um lugar onde eu possa me familiarizar com os comandos, posso tentar corrigir algumas coisas...

**Comment by douglasrizzo** [comment]
Eu percebi que o <> das URLs já foi removido na branch dev. Para as outras coisas, eu mandei algumas PRs com soluções que funcionaram nos meus casos #65 #66 #67.

Imagino que falte italicizar o _In_, mas não encontrei um jeito fácil de fazer isso ainda.

**Comment by dbmrq** [comment]
Maravilha, muito obrigado pela ajuda! Já já vou dar uma olhada nas PRs e faço o merge! Pelo jeito você já tá conseguindo se virar como BibLaTeX, mas a melhor fonte é o manual dele mesmo, seguido por questões aleatórias no StackExchange, rs. Eu escrevi o estilo com base nessas duas coisas e em outros estilos existentes, também não sabia (nem sei) quase nada!

**Comment by douglasrizzo** [comment]
Como tudo o que eu levantei nesse _issue_ (e mais um pouco) foi implementado, eu acho que podemos fechá-lo.

Só para informar a todos das alterações realizadas:

- As expressões _In_, _et al_, _s. l._ e _s. n._ foram colocadas em itálico. Faltavam espaços entre as letras nas siglas _s. l._ e _s. n._, os quais foram adicionados;
- O espaçamento entre linhas nas referências foi configurado como simples e o espaço entre entradas é o equivalente a uma linha em branco, cvomo mencionado na NBR 6023:2018;
- O travessão em nomes de autores repetidos foi removido, colocando-se a opção `repeatfields=true` como padrão. O comportamento antigo pode ser recuperado colocando `repeatfields=false`;
- Os colchetes em expressões como "**Anais [...]**" deve ser colocado manualmente no arquivo .bib. [Um exemplo](https://github.com/abntex/biblatex-abnt/blob/dev/bibtex/bib/biblatex-abnt/NBR6023-2018.bib) foi disponibilizado no repositório;
- Um PDF de referência com as mudanças pode ser visualizado [aqui](https://github.com/abntex/biblatex-abnt/blob/dev/tests/NBR6023-2018_reference.pdf) e comparado com um modelo ainda compilado sob a norma antiga [aqui](https://github.com/abntex/biblatex-abnt/blob/dev/tests/NBR6023-2002_reference.pdf).

**Comment by dbmrq** [comment]
Maravilha, muito obrigado por toda a ajuda!

**Comment by mvlp** [comment]
Prezados, 
Testei com o branch dev e o et al. não está em itálico. Pensei que era algum erro de configuração meu mas isso também ocorre no pdf de referência que o @douglasrizzo disponibilizou.

**Comment by fernandozucatelli** [comment]
Prezados.

Desde que a ABNT fez a atualização da  norma NBR 6023:2002 em 2018 eu vinha postergando minha migração do abntex2cite para o biblatex-abnt. Cheguei agora no ponto no qual preciso concluir minha migração e padronizar a sintaxe dos novos arquivos e casualmente alterar a de antigos que forem necessários.
Quando fui checar o resultado do bibilatex-abnt diante das atualizações de 2018, notei que algumas notórias como "<>" e itálicos em "et. al." e "In" não estavam sendo feitas na versão 3.4 de 2018-11-17 conforme estava na minha instalação e também no [CTAN-biblatex-abnt](https://www.ctan.org/pkg/biblatex-abnt). Vim verificar o GitHub e a versão mais atual descrita é a 3.4. Estranhei essa diferença e após pesquisar o dentro do GitHub encontrei essa _issue_ comentando sobre as mudanças para compatibilidade com a NBR 6023:2018. Baixei os arquivos do ramo _dev_, colei no local designado na minha instalação e a execução das normas está correta conforme a norma e também apresentado ao longo da _issue_.

Diante do exposto, por que vocês não criaram uma nova versão 3.5 (ou 4.0) que aplica a versão 2018 das normas e atualizaram os repositórios LaTeX?

Eu entendo que isso torna o uso do pacote e a aplicação das normas mais amigáveis.
Notem no entanto, que é mais fácil eu dizer para meus alunos e pares para baixarem a atualização do biblatex-abnt pelo gerenciador da instalação (MikTeX, TeXlive) do que dizer para baixarem pelo CTAN e fazer a instalação manual, o que ainda é mais fácil do que dizer para eles entrarem no GitHub e baixarem os arquivos de lá e então fazer a instalação manual.

Ademais, baixar o pacote **pronto** em qualquer um dos cenários é absolutamente mais fácil do que controlar essa ou aquela modificação feita nos arquivos da minha instalação, o que convenhamos não é qualquer modificação que possa ser facilmente executada dentro dos arquivos `.bst` ou `.bbx`,

Obrigado pela atenção e desculpem-me pelo longo comentário.

**Comment by dbmrq** [comment]
> Diante do exposto, por que vocês não criaram uma nova versão 3.5 (ou 4.0) que aplica a versão 2018 das normas e atualizaram os repositórios LaTeX?

Por um motivo muito simples; não tive tempo, rs.

**Comment by fernandozucatelli** [comment]
> > Diante do exposto, por que vocês não criaram uma nova versão 3.5 (ou 4.0) que aplica a versão 2018 das normas e atualizaram os repositórios LaTeX?
> 
> Por um motivo muito simples; não tive tempo, rs.

O Sr. conseguiria enviar a versão atual contida aqui no GitHub para ao menos o CTAN? Ao que me parece a versão aqui implementa as principais mudanças da norma. Nada muito complicado como uma revisão completa. Só o necessário para publicar o que já está no GitHub.
